name: Deploy Backend to Production

on:
  push:
    branches:
      - main-fulfillec

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_FULFILLEC }}
          username: ${{ secrets.SSH_USER_FULFILLEC }}
          password: ${{ secrets.SSH_PASSWORD_FULFILLEC }}
          port: 22
          script: |
            cd /www/wwwroot/storead.fulfillec.com
            git pull origin main-fulfillec
            bash deploy.sh